apiVersion: v1
kind: Service
metadata:
  name: selenium-server-service
  labels:
    appClass: selenium-server
  namespace: taf
spec:
  type: ClusterIP
  selector:
    appClass: selenium-server
  ports:
  - port: 4444
    targetPort: http
