apiVersion: v1
kind: Service
metadata:
  name: taf-frontend-service
  labels:
    appClass: taf-frontend
  namespace: taf
spec:
  type: LoadBalancer
  selector:
    appClass: taf-frontend
  ports:
    - port: 4200
      targetPort: http
