import {
  Button,
  Divider,
  FormControl,
  FormHelperText,
  FormLabel,
  Heading,
  HStack,
  Input,
  Text,
  VStack,
} from "@chakra-ui/react";
import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Heading>Tests UI</Heading>

        <VStack my={10}>
          <FormControl>
            <FormLabel>URL</FormLabel>
            <Input borderColor="blue.500"/>
            <FormHelperText>Entrer l'URL du site web à tester</FormHelperText>
          </FormControl>
          <Divider />
          <VStack>
            <Heading as="h2" size="md" marginRight="auto !important">
              Test #1
            </Heading>
            <Text>
              Si l'utilisateur clique sur un bouton nommé <Input borderColor="blue.500"/>
              Alors dans la page du navigateur, ce texte sera affiché: <Input borderColor="blue.500"/>
            </Text>
          </VStack>
          <Divider />
          <VStack marginRight="auto !important">
            <Heading as="h2" size="md" marginRight="auto !important">
              Test #2
            </Heading>
            <Text>
              Un élément H1 est présent dans la page et contient le texte
              suivant: <Input borderColor="blue.500"/>
            </Text>
          </VStack>

          <Button colorScheme="blue" marginRight="auto !important">Tester</Button>
        </VStack>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Équipe 1
        </a>
      </footer>
    </div>
  );
}
