import {
  Box,
  Button,
  Divider,
  Grid,
  Heading,
  HStack,
  Link,
  Tag,
  VStack,
} from "@chakra-ui/react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Project from "../types/Project";
import { AddIcon } from "@chakra-ui/icons";

const exampleProjects: Project[] = [
  {
    name: "TAF",
    owner: "John Doe",
    start: new Date(2022, 10, 11),
    end: new Date(2022, 10, 15),
  },
  {
    name: "Projet 2",
    owner: "Christina",
    start: new Date(2022, 11, 11),
    end: new Date(2022, 11, 15),
  },
];

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Heading>Tests UI</Heading>

        <VStack my={10}>
          <HStack>
            <Button colorScheme="blue" leftIcon={<AddIcon />}>
              <Link href="/projects/new">Nouveau projet</Link>
            </Button>
          </HStack>
        </VStack>

        <Divider my={5} />

        <Grid templateColumns="repeat(5, 1fr)" gap={6}>
          {exampleProjects.map((project) => (
            <Box backgroundColor="blue.100" p={3} borderRadius={5} border="1px solid black">
              <VStack>
                <p>
                  <strong>{project.name}</strong>
                </p>
                <p>Responsable: {project.owner}</p>
                <Tag size="lg" variant="solid" colorScheme="blue">
                  {project.start.toLocaleDateString()} -{" "}
                  {project.end.toLocaleDateString()}
                </Tag>
              </VStack>
            </Box>
          ))}
        </Grid>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Équipe 1
        </a>
      </footer>
    </div>
  );
}
