name: build-and-deploy
run-name: Build and deploy

on:
  push:
    branches:
      - "develop"

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - run: ./mvnw package
      - uses: actions/upload-artifact@v3
        with:
          name: backend-jar
          path: backend/target/backend-1.0.0-SNAPSHOT.jar
  deploy-taf:
    runs-on: ubuntu-latest
    needs: build-backend
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
        with:
          name: backend-jar
          path: backend/target/backend-1.0.0-SNAPSHOT.jar
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm
          cache-dependency-pack: pulumi/aws-eks/package-lock.json
      - run: npm install --prefix pulumi/aws-eks
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: mgl805/aws-eks/dev
          work-dir: pulumi/aws-eks
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  # deploy-wikijs:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: 16.x
  #         cache: yarn
  #         cache-dependency-path: pulumi/google-cloud/yarn.lock
  #     - run: yarn --cwd pulumi/google-cloud install
  #     - id: 'auth'
  #       name: 'Authenticate to Google Cloud'
  #       uses: 'google-github-actions/auth@v0'
  #       with:
  #         credentials_json: '${{ secrets.GCP_GITHUB_SA_KEY }}'
  #     - uses: pulumi/actions@v3
  #       with:
  #         command: up
  #         stack-name: mgl805/google-cloud/dev
  #         work-dir: pulumi/google-cloud
  #       env:
  #         PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
